// components/Team.vue
<template>
  <section>
    <div
      class="mx-auto max-w-screen-xl px-4 py-8 @container @lg:px-6 @lg:py-16">
      <SectionTitle
        title="Our Team"
        description="EternalCodeTeam is a dedicated group of creative programmers who work on unique open source projects."
      />

      <div class="mb-6 grid gap-8 @md:grid-cols-2 @lg:mb-16">
        <div
          v-for="(member, index) in teamMembers"
          :key="index"
          class="mx-auto mb-8 max-w-screen-md flex-1 @lg:mb-16"
          data-aos="fade-up"
          data-aos-duration="450">
          <div
            class="flex-1 items-center rounded-[12px] bg-gray-50 shadow @sm:flex dark:border-gray-700 dark:bg-[#161b22]">
            <a
              :href="member.github"
              class="aspect-w-1 aspect-h-1 container sm:w-full sm:max-w-[32rem]">
              <NuxtImg
                :alt="member.name"
                :src="member.avatar"
                class="object-cover @sm:rounded-none @sm:rounded-l-lg"
                format="webp"
                height="400"
                width="400" />
            </a>
            <div class="p-8">
              <h3
                class="text-xl font-bold tracking-tight text-gray-900 dark:text-white">
                {{ member.name }}
              </h3>
              <span class="text-gray-500 dark:text-gray-400">
                {{ member.role }}
              </span>
              <p class="mb-4 mt-3 font-light text-gray-500 dark:text-gray-400">
                {{ member.bio }}
              </p>
              <ul class="flex space-x-4 @sm:mt-0">
                <li v-if="member.github">
                  <a
                    :href="member.github"
                    aria-label="Github profile link"
                    class="text-gray-500 transition duration-500 hover:text-gray-900 dark:hover:text-white">
                    <font-awesome-icon :icon="['fab', 'github']" />
                  </a>
                </li>
                <li v-if="member.linkedin">
                  <a
                    :href="member.linkedin"
                    aria-label="LinkedIn profile link"
                    class="text-gray-500 transition duration-500 hover:text-gray-900 dark:hover:text-white">
                    <font-awesome-icon :icon="['fab', 'linkedin']" />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

export default {
  components: { FontAwesomeIcon },
  data() {
    return {
      teamMembers: [
        {
          name: "Martin Sulikowski",
          role: "Lead Team",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/65517973?v=4",
          github: "https://github.com/vLuckyyy",
          linkedin: "https://www.linkedin.com/in/vlucky",
        },
        {
          name: "Norbert Dejlich",
          role: "Lead Team & Meeting Leader",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/49173834?v=4",
          github: "https://github.com/Rollczi/",
          linkedin: "https://www.linkedin.com/in/rollczi/",
        },
        {
          name: "Krzysztof Haller",
          role: "Lead Team",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/60399586?v=4",
          github: "https://github.com/Hyd3r1/",
          linkedin: "https://www.linkedin.com/in/khallercom/",
        },
        {
          name: "Piotr Zych",
          role: "Lead Team, Meeting Leader & Team Manager",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/77621271?v=4",
          github: "https://github.com/Osnixer/",
        },
        {
          name: "Jakub",
          role: "Discord Moderator & Team Developer",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/77227023?v=4",
          github: "https://github.com/Jakubk15",
        },
        {
          name: "Karol Dronia",
          role: "Team Developer",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/80169196?v=4",
          github: "https://github.com/eripe14",
        },
        {
          name: "Kamil Jęczeń",
          role: "Team Developer",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/66566758?v=4",
          github: "https://github.com/Kamicjusz",
        },
        {
          name: "Michał Wojtas",
          role: "Student & Team Analyst",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/80779749?v=4",
          github: "https://github.com/Embrejs",
        },
      ],
    };
  },
};
</script>

// components/team/Team.tsx
"use client";

import React, { useEffect, useState } from "react";
import SectionTitle from "@/components/SectionTitle";
import Image from "next/image";
import { motion, useAnimation } from "framer-motion";
import GitHubIcon from "../icons/github";
import LinkedinIcon from "../icons/linkedin";

interface TeamRole {
  attributes: {
    name: string;
  };
}

interface MemberData {
  avatar_url: string;
  name: string;
  team_roles: {
    data: TeamRole[];
  };
  github?: string;
  linkedin?: string;
}

interface TeamMemberProps {
  member: MemberData;
  index: number;
}

interface Member {
  id: string;
  attributes: {
    avatar_url: string;
    name: string;
    team_roles: {
      data: TeamRole[];
    };
    github?: string;
    linkedin?: string;
  };
}

export default function Team() {
  const [members, setMembers] = useState<Member[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchMembers = async () => {
      try {
        const response = await fetch("/api/team");

        if (!response.ok) {
          throw new Error("Failed to fetch team members");
        }

        const data = (await response.json()) as { data: Member[] };

        if (data && data.data) {
          setMembers(data.data);
        } else {
          throw new Error("Invalid data structure in API response");
        }
      } catch (error) {
        const err = error as Error;
        setError(err.message);
        console.error("Error fetching team members:", err);
      }
    };

    fetchMembers();
  }, []);

  if (error) {
    return <div>{error}</div>;
  }

  return (
    <section id="team">
      <div className="mx-auto max-w-screen-xl px-4 py-16">
        <SectionTitle
          title="Our Team"
          description="EternalCodeTeam is a dedicated group of creative programmers who work on unique open source projects."
        />

        <div
          className={`mt-8 grid grid-cols-1 gap-8 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4`}
        >
          {members.map((member, index) => (
            <TeamMember
              key={member.id}
              member={member.attributes}
              index={index}
            />
          ))}
        </div>
      </div>
    </section>
  );
}

export function TeamMember({ member, index }: TeamMemberProps) {
  const controls = useAnimation();

  useEffect(() => {
    controls.start({ opacity: 1, y: 0 });
  }, [controls]);

  return (
    <motion.div
      key={index}
      className="text-center text-gray-500 dark:text-gray-400"
      initial={{ opacity: 0, y: 30 }}
      animate={controls}
      transition={{ duration: 0.1, delay: index * 0.1 }}
    >
      <Image
        className="mx-auto mb-4 h-36 w-36 rounded-full"
        src={member.avatar_url}
        alt={`${member.name} Avatar`}
        title={member.name}
        width={144}
        height={144}
      />

      <h3 className="mb-1 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
        {member.name}
      </h3>

      {member.team_roles.data.map((role, roleIndex) => (
        <p key={roleIndex}>{role.attributes.name}</p>
      ))}

      <ul className="mt-4 flex justify-center space-x-4">
        {member.github && (
          <li>
            <a
              href={member.github}
              className="transition duration-500 hover:text-gray-900 dark:hover:text-white"
            >
              <GitHubIcon />
            </a>
          </li>
        )}

        {member.linkedin && (
          <li>
            <a
              href={member.linkedin}
              className="transition duration-500 hover:text-gray-900 dark:hover:text-white"
            >
              <LinkedinIcon />
            </a>
          </li>
        )}
      </ul>
    </motion.div>
  );
}
