// components/hero/Hero.vue
<template>
  <div class="relative isolate px-6 pt-14 lg:px-8">
    <PolygonLeft />

    <div
      class="mx-auto flex flex-col-reverse lg:flex-row max-w-screen-xl py-8 pl-2 md:w-full md:items-center md:justify-center lg:gap-8 lg:py-16 xl:gap-0">
      <div class="place-self-center md:ml-0 lg:col-span-4 lg:mr-auto">
        <h1
          class="max-w-2xl text-center mb-4 text-4xl font-extrabold tracking-tight leading-none md:text-5xl xl:text-6xl dark:text-white"
          data-aos="fade-up"
          data-aos-duration="500">
          {{ $t("welcome") }}
        </h1>
        <p
          class="max-w-2xl mb-6 ml-[3px] font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400"
          data-aos="fade-up"
          data-aos-duration="550">
          {{ $t("subwelcome") }}
        </p>
        <div
          class="flex flex-col items-center justify-center pr-4 sm:flex-row md:p-0 lg:block">
          <NuxtLink :to="localePath('/#about')">
            <button
              :aria-label="`${$t('firstButton')} button`"
              class="mb-2 mr-2 pr-5 py-2.5 text-left text-sm font-medium text-black dark:text-white">
              <Icon name="material-symbols:arrow-forward" class="mb-[0.5px]" />
              {{ $t("firstButton") }}
            </button>
          </NuxtLink>

          <NuxtLink :to="localePath('/team')">
            <button
              :aria-label="`${$t('secondButton')} button`"
              class="mb-2 mr-2 rounded-lg bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 px-5 py-2.5 text-center text-sm font-medium text-white shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80">
              <Icon name="material-symbols:groups" class="mb-[0.5px]" />
              {{ $t("secondButton") }}
            </button>
          </NuxtLink>
        </div>
      </div>

      <div class="hidden lg:col-span-8 w-full lg:block lg:pl-36 lg:pr-0 px-20">
        <Terminal />
      </div>
      <PolygonRight />
    </div>
  </div>
</template>

<script setup>
import PolygonRight from "~/components/hero/PolygonRight.vue";
import PolygonLeft from "~/components/hero/PolygonLeft.vue";
import Terminal from "~/components/hero/terminal/Terminal.vue";
</script>

// components/hero/Hero.tsx
"use client";

import { AnimatedSection, AnimatedElement, AnimatedContainer } from "@/components/animations";
import BackgroundHeroButton from "@/components/hero/button/BackgroundHeroButton";
import TransparentHeroButton from "@/components/hero/button/TransparentHeroButton";
import Terminal from "@/components/hero/terminal/Terminal";

export default function Hero() {
  return (
    <AnimatedSection
      className="relative mx-auto mt-16 max-w-screen-xl px-4 pt-20 lg:pt-28"
      animationType="fade"
      aria-labelledby="hero-heading"
    >
      <div className="flex flex-col-reverse items-center justify-center gap-8 py-8 md:flex-row lg:py-16">
        <div className="text-center lg:text-left">
          <AnimatedElement
            as="h1"
            id="hero-heading"
            className="mb-4 max-w-2xl text-4xl font-extrabold leading-none tracking-tight dark:text-white md:text-5xl lg:mb-6 lg:text-6xl"
            animationType="fadeDown"
            delay={0.1}
          >
            EternalCode.pl
          </AnimatedElement>

          <AnimatedElement
            as="p"
            className="mb-6 ml-[3px] max-w-2xl font-light text-gray-500 dark:text-gray-400 md:text-lg lg:mb-8 lg:text-xl"
            animationType="fadeUp"
            delay={0.2}
          >
            We are a team creating open source projects!
          </AnimatedElement>

          <AnimatedContainer
            className="flex flex-row justify-center lg:justify-start"
            staggerDelay={0.1}
            delay={0.3}
          >
            <AnimatedElement as="div" animationType="fadeLeft" interactive={true}>
              <TransparentHeroButton />
            </AnimatedElement>

            <AnimatedElement as="div" animationType="fadeRight" interactive={true}>
              <BackgroundHeroButton />
            </AnimatedElement>
          </AnimatedContainer>
        </div>

        <AnimatedElement
          as="div"
          className="hidden w-full px-20 lg:col-span-8 lg:block lg:pl-36 lg:pr-0"
          animationType="fadeLeft"
          delay={0.4}
        >
          <Terminal />
        </AnimatedElement>
      </div>
    </AnimatedSection>
  );
}
