// components/hero/Navbar.tsx
"use client";

import { AnimatePresence, motion } from "framer-motion";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";

import AnnouncementBanner from "@/components/hero/AnnouncementBanner";
import { Button } from "@/components/ui/button";
import logo from "@/public/logo.svg";

import ArrowDown from "../icons/arrow-down";
import Hamburger from "../icons/hamburger";
import NewWindow from "../icons/new-window";

import ThemeSwitchButton from "./ThemeSwitchButton";
import { ToolsDropdown } from "./ToolsDropdown";

interface NavLink {
  href: string;
  label: string;
  text: string;
  isExternal?: boolean;
}

const NAV_LINKS: NavLink[] = [
  { href: "/", label: "Home", text: "Home" },
  { href: "/team", label: "Team", text: "Team" },
  { href: "/projects", label: "Projects", text: "Projects" },
  { href: "/docs", label: "Documentation", text: "Documentation" },
  { href: "/blog", label: "Blog", text: "Blog" },
  {
    href: "https://repo.eternalcode.pl/#/",
    label: "Repository",
    text: "Repository",
    isExternal: true,
  },
  {
    href: "https://status.eternalcode.pl/",
    label: "Status",
    text: "Status",
    isExternal: true,
  },
];

export default function Navbar() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const navRef = useRef<HTMLElement>(null);
  const menuButtonRef = useRef<HTMLButtonElement>(null);

  const toggleMenu = useCallback(() => {
    setIsMenuOpen((prev) => !prev);
  }, []);

  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isMenuOpen) {
        setIsMenuOpen(false);
        menuButtonRef.current?.focus();
      }
    };

    document.addEventListener("keydown", handleEscape);
    return () => document.removeEventListener("keydown", handleEscape);
  }, [isMenuOpen]);

  useEffect(() => {
    if (isMenuOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "unset";
    }
    return () => {
      document.body.style.overflow = "unset";
    };
  }, [isMenuOpen]);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (navRef.current && !navRef.current.contains(event.target as Node) && isMenuOpen) {
        setIsMenuOpen(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [isMenuOpen]);

  return (
    <nav
      ref={navRef}
      className="fixed inset-x-0 top-0 z-50 border-b border-gray-200 bg-lightGray-100 backdrop-blur-md dark:border-gray-800 dark:bg-gray-900"
      role="navigation"
      aria-label="Main navigation"
    >
      <AnnouncementBanner />

      <div className="mx-auto flex max-w-screen-xl flex-wrap items-center justify-between px-4 py-4 md:py-6">
        <Link href="/" className="flex items-center" aria-label="Go to homepage">
          <Image
            className="mr-3 h-8 w-auto dark:invert"
            alt="EternalCode Logo"
            src={logo}
            width={32}
            height={32}
            priority
          />
          <span className="hidden self-center whitespace-nowrap text-2xl font-semibold text-black dark:text-white md:block">
            EternalCode.pl
          </span>
        </Link>

        <div className="flex items-center justify-center md:order-2">
          <ThemeSwitchButton />

          <Button
            ref={menuButtonRef}
            variant="ghost"
            size="sm"
            className="ml-1 inline-flex items-center p-2 text-sm dark:text-white md:hidden"
            type="button"
            aria-label="Toggle menu"
            aria-controls="mobile-menu"
            aria-expanded={isMenuOpen}
            onClick={toggleMenu}
          >
            <motion.div
              initial={false}
              animate={isMenuOpen ? "open" : "closed"}
              transition={{ duration: 0.2 }}
            >
              {isMenuOpen ? (
                <ArrowDown className="h-5 w-5" aria-hidden="true" />
              ) : (
                <Hamburger className="h-5 w-5" aria-hidden="true" />
              )}
            </motion.div>
          </Button>
        </div>

        <AnimatePresence>
          {isMenuOpen && (
            <motion.div
              id="mobile-menu"
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.2 }}
              className="w-full md:hidden"
              role="menu"
            >
              <ul className="mt-4 flex flex-col space-y-1 p-4">
                {NAV_LINKS.slice(0, 5).map((link) => (
                  <motion.li
                    key={link.href}
                    initial={{ x: -20, opacity: 0 }}
                    animate={{ x: 0, opacity: 1 }}
                    transition={{ duration: 0.2 }}
                  >
                    <Link
                      href={link.href}
                      className="flex items-center justify-center rounded-full px-4 py-1.5 text-gray-900 transition-colors duration-200 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-800"
                      aria-label={link.label}
                      target={link.isExternal ? "_blank" : undefined}
                      rel={link.isExternal ? "noopener noreferrer" : undefined}
                      onClick={() => setIsMenuOpen(false)}
                    >
                      {link.text}
                      {link.isExternal && <NewWindow className="ml-1" aria-hidden="true" />}
                    </Link>
                  </motion.li>
                ))}
                <motion.li
                  initial={{ x: -20, opacity: 0 }}
                  animate={{ x: 0, opacity: 1 }}
                  transition={{ duration: 0.2 }}
                >
                  <ToolsDropdown />
                </motion.li>
                {NAV_LINKS.slice(5).map((link) => (
                  <motion.li
                    key={link.href}
                    initial={{ x: -20, opacity: 0 }}
                    animate={{ x: 0, opacity: 1 }}
                    transition={{ duration: 0.2 }}
                  >
                    <Link
                      href={link.href}
                      className="flex items-center justify-center rounded-full px-4 py-1.5 text-gray-900 transition-colors duration-200 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-800"
                      aria-label={link.label}
                      target={link.isExternal ? "_blank" : undefined}
                      rel={link.isExternal ? "noopener noreferrer" : undefined}
                      onClick={() => setIsMenuOpen(false)}
                    >
                      {link.text}
                      {link.isExternal && <NewWindow className="ml-1" aria-hidden="true" />}
                    </Link>
                  </motion.li>
                ))}
              </ul>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="hidden w-full items-center justify-between md:order-1 md:flex md:w-auto">
          <ul className="mt-4 flex flex-col space-y-2 md:mt-0 md:flex-row md:space-x-2 md:space-y-0 md:p-0">
            {NAV_LINKS.slice(0, 5).map((link) => (
              <li key={link.href}>
                <Link
                  href={link.href}
                  className="flex items-center justify-center rounded-full px-4 py-1.5 text-gray-900 transition-colors duration-200 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-800"
                  aria-label={link.label}
                  target={link.isExternal ? "_blank" : undefined}
                  rel={link.isExternal ? "noopener noreferrer" : undefined}
                >
                  {link.text}
                  {link.isExternal && <NewWindow className="ml-1" aria-hidden="true" />}
                </Link>
              </li>
            ))}
            <li>
              <ToolsDropdown />
            </li>
            {NAV_LINKS.slice(5).map((link) => (
              <li key={link.href}>
                <Link
                  href={link.href}
                  className="flex items-center justify-center rounded-full px-4 py-1.5 text-gray-900 transition-colors duration-200 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-800"
                  aria-label={link.label}
                  target={link.isExternal ? "_blank" : undefined}
                  rel={link.isExternal ? "noopener noreferrer" : undefined}
                >
                  {link.text}
                  {link.isExternal && <NewWindow className="ml-1" aria-hidden="true" />}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </nav>
  );
}

// components/Navbar.vue
<template>
  <div class="bg-white">
    <div class="fixed inset-x-0 top-0 z-50">
      <nav
        class="border-gray-200 bg-transparent backdrop-blur-md backdrop-filter">
        <div
          class="mx-auto flex max-w-screen-xl flex-wrap items-center justify-between p-4">
          <NuxtLink class="flex items-center" to="/">
            <NuxtImg
              alt="Eternalcode Logo"
              class="mr-3 h-8 text-white dark:invert"
              format="svg"
              height="32"
              src="/assets/img/logo.svg"
              width="32" />
            <span
              class="hidden self-center whitespace-nowrap text-2xl font-semibold dark:text-white md:block">
              EternalCode.pl
            </span>
          </NuxtLink>

          <div class="flex items-center md:order-2">
            <ThemeSwitchButton />

            <button
              aria-controls="mobile-menu-language-select"
              aria-expanded="false"
              aria-label="Menu"
              class="ml-1 inline-flex items-center rounded-lg p-2 text-sm dark:text-white md:hidden"
              data-collapse-toggle="mobile-menu-language-select"
              type="button">
              <font-awesome-icon :icon="['fa', 'bars']" class="h-6 w-6" />
            </button>
          </div>

          <div
            id="mobile-menu-language-select"
            class="hidden w-full items-center justify-between md:order-1 md:flex md:w-auto">
            <ul
              class="mt-4 flex flex-col p-4 md:mt-0 md:flex-row md:space-x-8 md:p-0">
              <li v-for="item in navigation" :key="item.name">
                <NuxtLink
                  :to="item.href"
                  class="block rounded-full py-2 pl-3 pr-4 text-gray-900 dark:text-white md:p-0">
                  {{ item.name }}
                </NuxtLink>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</template>

<script lang="ts">
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

export default {
  components: { FontAwesomeIcon },
  data() {
    return {
      navigation,
    };
  },
};

const navigation = [
  { name: "Home", href: "/" },
  { name: "Our Team", href: "/team" },
  { name: "Our projects", href: "/projects" },
  { name: "Documentations", href: "https://docs.eternalcode.pl/" },
  { name: "Status", href: "https://status.eternalcode.pl/" },
  { name: "Repository", href: "https://repo.eternalcode.pl/#/" },
];
</script>
