// components/section/SectionTitle.vue
<template>
  <div class="mx-auto mb-8 lg:mb-16">
    <div class="flex flex-col lg:flex-row justify-between items-center">
      <div class="lg:w-1/2">
        <h2
          class="text-4xl font-extrabold tracking-tight text-gray-900 dark:text-white mb-4 lg:mb-0 lg:mr-8">
          {{ title }}
        </h2>
      </div>
      <div class="lg:w-1/2">
        <p
          class="font-light text-gray-500 text-xl dark:text-gray-400 text-center lg:text-right break-words">
          {{ description }}
        </p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "SectionTitle",
  props: {
    title: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      required: true,
    },
  },
};
</script>

// components/SectionTitle.tsx
import React from "react";

export default function SectionTitle({
  title,
  description,
}: Readonly<{
  title: string;
  description: string;
}>) {
  return (
    <div className="flex flex-col items-center justify-between lg:flex-row">
      <div className="lg:w-1/2">
        <h2 className="mb-4 break-words text-center text-4xl font-extrabold tracking-tight text-gray-900 dark:text-white lg:mb-0 lg:mr-8 lg:text-left">
          {title}
        </h2>
      </div>
      <div className="lg:w-1/2">
        <p className="break-words text-center text-xl font-light text-gray-500 dark:text-gray-400 lg:text-right">
          {description}
        </p>
      </div>
    </div>
  );
}
