// components/team/team.tsx
import Image from "next/image";
import { SlideIn, StaggerContainer } from "@/components/ui/motion/motion-components";
import { getTeamData } from "@/lib/team";
import TeamMember from "./team-member";

export default async function Team() {
  const sections = await getTeamData();

  return (
    <section id="team">
      <div className="relative mx-auto max-w-[90rem] px-4 pt-4 pb-20">
        <div className="mt-8 space-y-20">
          {sections.map((section) => (
            <div key={section.name}>
              <SlideIn className="mb-8" direction="up">
                <h2 className="font-bold text-2xl text-gray-900 dark:text-white">
                  {section.name.endsWith("s") ? section.name : `${section.name}s`}
                </h2>
                <p className="mt-2 max-w-2xl text-base text-gray-600 dark:text-gray-400">
                  {section.description}
                </p>
              </SlideIn>

              {section.variant === "contributors" ? (
                <StaggerContainer className="flex flex-wrap gap-4">
                  {section.members.map((member, index) => (
                    <SlideIn
                      delay={index * 0.01}
                      direction="up"
                      key={`${section.name}-${member.documentId || index}`}
                    >
                      <a
                        aria-label={`View ${member.name}'s GitHub profile`}
                        className="group relative block"
                        href={member.github}
                        rel="noopener noreferrer"
                        target="_blank"
                        title={member.name}
                      >
                        <div className="relative h-16 w-16 overflow-hidden rounded-full border-2 border-gray-200 shadow-sm transition-transform duration-300 group-hover:scale-110 group-hover:shadow-md dark:border-gray-800">
                          <Image
                            alt={`Profile picture of ${member.name}`}
                            className="h-full w-full object-cover"
                            height={64}
                            loading={index > 8 ? "lazy" : undefined}
                            src={member.avatar_url}
                            width={64}
                          />
                        </div>
                      </a>
                    </SlideIn>
                  ))}
                </StaggerContainer>
              ) : (
                <StaggerContainer className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
                  {section.members.map((member, index) => (
                    <SlideIn
                      delay={index * 0.05}
                      direction="up"
                      key={`${section.name}-${member.documentId || index}`}
                    >
                      <TeamMember index={index} member={member} />
                    </SlideIn>
                  ))}
                </StaggerContainer>
              )}
            </div>
          ))}

          {sections.length === 0 && (
            <div className="mt-12 text-center text-gray-500">
              No team members yet. Check back soon!
            </div>
          )}
        </div>
      </div>
    </section>
  );
}

// components/Team.vue
<template>
  <section>
    <div
      class="mx-auto max-w-screen-xl px-4 py-8 @container @lg:px-6 @lg:py-16">
      <SectionTitle
        title="Our Team"
        description="EternalCodeTeam is a dedicated group of creative programmers who work on unique open source projects."
      />

      <div class="mb-6 grid gap-8 @md:grid-cols-2 @lg:mb-16">
        <div
          v-for="(member, index) in teamMembers"
          :key="index"
          class="mx-auto mb-8 max-w-screen-md flex-1 @lg:mb-16"
          data-aos="fade-up"
          data-aos-duration="450">
          <div
            class="flex-1 items-center rounded-[12px] bg-gray-50 shadow @sm:flex dark:border-gray-700 dark:bg-[#161b22]">
            <a
              :href="member.github"
              class="aspect-w-1 aspect-h-1 container sm:w-full sm:max-w-[32rem]">
              <NuxtImg
                :alt="member.name"
                :src="member.avatar"
                class="object-cover @sm:rounded-none @sm:rounded-l-lg"
                format="webp"
                height="400"
                width="400" />
            </a>
            <div class="p-8">
              <h3
                class="text-xl font-bold tracking-tight text-gray-900 dark:text-white">
                {{ member.name }}
              </h3>
              <span class="text-gray-500 dark:text-gray-400">
                {{ member.role }}
              </span>
              <p class="mb-4 mt-3 font-light text-gray-500 dark:text-gray-400">
                {{ member.bio }}
              </p>
              <ul class="flex space-x-4 @sm:mt-0">
                <li v-if="member.github">
                  <a
                    :href="member.github"
                    aria-label="Github profile link"
                    class="text-gray-500 transition duration-500 hover:text-gray-900 dark:hover:text-white">
                    <font-awesome-icon :icon="['fab', 'github']" />
                  </a>
                </li>
                <li v-if="member.linkedin">
                  <a
                    :href="member.linkedin"
                    aria-label="LinkedIn profile link"
                    class="text-gray-500 transition duration-500 hover:text-gray-900 dark:hover:text-white">
                    <font-awesome-icon :icon="['fab', 'linkedin']" />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

export default {
  components: { FontAwesomeIcon },
  data() {
    return {
      teamMembers: [
        {
          name: "Martin Sulikowski",
          role: "Lead Team",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/65517973?v=4",
          github: "https://github.com/vLuckyyy",
          linkedin: "https://www.linkedin.com/in/vlucky",
        },
        {
          name: "Norbert Dejlich",
          role: "Lead Team & Meeting Leader",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/49173834?v=4",
          github: "https://github.com/Rollczi/",
          linkedin: "https://www.linkedin.com/in/rollczi/",
        },
        {
          name: "Krzysztof Haller",
          role: "Lead Team",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/60399586?v=4",
          github: "https://github.com/Hyd3r1/",
          linkedin: "https://www.linkedin.com/in/khallercom/",
        },
        {
          name: "Piotr Zych",
          role: "Lead Team, Meeting Leader & Team Manager",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/77621271?v=4",
          github: "https://github.com/Osnixer/",
        },
        {
          name: "Jakub",
          role: "Discord Moderator & Team Developer",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/77227023?v=4",
          github: "https://github.com/Jakubk15",
        },
        {
          name: "Karol Dronia",
          role: "Team Developer",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/80169196?v=4",
          github: "https://github.com/eripe14",
        },
        {
          name: "Kamil Jęczeń",
          role: "Team Developer",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/66566758?v=4",
          github: "https://github.com/Kamicjusz",
        },
        {
          name: "Michał Wojtas",
          role: "Student & Team Analyst",
          bio: "Consetetur feugait semper pellentesque nihil intellegebat interdum ultricies noster.",
          avatar: "https://avatars-githubusercontent.webp.se/u/80779749?v=4",
          github: "https://github.com/Embrejs",
        },
      ],
    };
  },
};
</script>
