// components/About.vue
<template>
  <section class="py-14">
    <div class="mx-auto max-w-screen-xl px-4 py-8">
      <div class="items-center gap-x-12 sm:px-4 md:px-0 lg:flex">
        <div class="flex-1 sm:hidden lg:block">
          <NuxtImg
            src="https://www.eternalcode.pl/assets/img/header/about/eternalcore-intellij.webp"
            class="rounded-[12px]"
            alt="about me presentation"
            data-aos="fade-up"
            data-aos-duration="450" />
        </div>
        <div class="max-w-xl px-4 space-y-3 mt-6 sm:px-0 md:mt-0 lg:max-w-2xl">
          <p
            class="text-4xl font-extrabold tracking-tight text-gray-900 dark:text-white mb-4 lg:mb-0 lg:mr-8"
            data-aos="fade-up"
            data-aos-duration="500">
            {{ $t("about.title") }}
            <Icon name="ph:terminal-fill" class="mb-2" />
          </p>
          <p
            class="font-light text-gray-500 text-xl dark:text-gray-400"
            data-aos="fade-up"
            data-aos-duration="550">
            {{ $t("about.text") }}
          </p>

          <p
            class="font-light text-gray-500 text-xl dark:text-gray-400"
            data-aos="fade-up"
            data-aos-duration="550">
            {{ $t("about.text2") }}
          </p>

          <ul class="flex gap-y-6 flex-wrap items-center justify-center">
            <li class="flex-none" data-aos="fade-up" data-aos-duration="600">
              <a href="https://github.com">
                <Icon
                  name="akar-icons:github-fill"
                  size="48"
                  class="m-4 text-black dark:text-white" />
              </a>
            </li>

            <li class="flex-none" data-aos="fade-up" data-aos-duration="650">
              <a href="https://www.jetbrains.com">
                <Icon name="logos:jetbrains" size="48" class="m-4" />
              </a>
            </li>

            <li class="flex-none" data-aos="fade-up" data-aos-duration="700">
              <a href="https://sentry.io">
                <Icon
                  name="vscode-icons:file-type-sentry"
                  size="48"
                  class="m-4" />
              </a>
            </li>

            <li class="flex-none" data-aos="fade-up" data-aos-duration="750">
              <a href="https://www.atlassian.com/software/jira">
                <Icon name="logos:jira" size="48" class="m-4" />
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
</template>

// components/about/About.tsx
"use client";

import { motion } from "framer-motion";
import Image from "next/image";
import TerminalIcon from "../icons/terminal-fill";
import AboutImage from "@/public/hero image.png";

import { useInView } from "react-intersection-observer";
import { useMemo } from "react";

const Container = ({ children }: { children: React.ReactNode }) => (
  <div className="mx-auto max-w-screen-xl px-4 py-8">{children}</div>
);

export default function About() {
  const combineVariants = useMemo(
    () => ({
      hidden: { opacity: 0 },
      show: {
        opacity: 1,
        transition: {
          duration: 0.3,
        },
      },
    }),
    []
  );

  const { ref: section, inView: inView1 } = useInView({ triggerOnce: false });
  const { ref: div, inView: inView2 } = useInView({ triggerOnce: false });
  const { ref: img, inView: inView3 } = useInView({ triggerOnce: false });

  return (
    <motion.section
      id="about"
      className="py-16"
      ref={section}
      variants={combineVariants}
      initial="hidden"
      animate={inView1 ? "show" : "hidden"}
    >
      <Container>
        <div className="mx-auto items-center gap-x-12 sm:px-4 md:px-0 lg:flex">
          <motion.div
            className="mx-auto flex-1 sm:hidden lg:block"
            ref={img}
            variants={combineVariants}
            initial="hidden"
            animate={inView3 ? "show" : "hidden"}
          >
            <Image
              src={AboutImage}
              className="mx-auto rounded-[12px]"
              height={500}
              width={1000}
              priority={true}
              decoding="async"
              alt="about me presentation"
            />
          </motion.div>
          <motion.div
            ref={div}
            variants={combineVariants}
            initial="hidden"
            animate={inView2 ? "show" : "hidden"}
            className="mx-auto mt-6 max-w-xl space-y-3 px-4 sm:px-0 md:mt-0 lg:max-w-2xl"
          >
            <motion.p className="mx-auto mb-4 text-4xl font-extrabold tracking-tight text-gray-900 dark:text-white md:text-center lg:mb-0 lg:mr-8 lg:text-left">
              <span className="flex items-center justify-center md:justify-center lg:justify-start">
                About us
                <TerminalIcon className="ml-2" />
              </span>
            </motion.p>
            <motion.p className="mx-auto text-center text-gray-500 dark:text-gray-400 lg:text-left">
              We are a team of programmers specializing in open-source projects.
              This allows us to gain new experiences and share knowledge with
              each other. We are open to any technology!
            </motion.p>

            <motion.p className="mx-auto text-center text-gray-500 dark:text-gray-400 lg:text-left">
              Special thanks to JetBrains, Sentry.io and Jira Software for
              providing open-source licenses to our team members. We would also
              like to express our gratitude to GitHub for providing high-quality
              software for managing Git repositories.
            </motion.p>
          </motion.div>
        </div>
      </Container>
    </motion.section>
  );
}
